-- MySQL Script generated by MySQL Workbench
-- Tue Jun 20 08:28:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema moviealert
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moviealert
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moviealert` DEFAULT CHARACTER SET utf8 ;
USE `moviealert` ;

-- -----------------------------------------------------
-- Table `moviealert`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviealert`.`filme` (
  `idfilme` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `diretor` VARCHAR(45) NULL,
  `data_lancamento` DATE NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfilme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviealert`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviealert`.`login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(20) NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idlogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviealert`.`preferencia_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviealert`.`preferencia_usuario` (
  `idpreferencia_usuario` INT NOT NULL AUTO_INCREMENT,
  `idfilme` INT NULL,
  `idlogin` INT NULL,
  INDEX `fk_filme_has_login_login1_idx` (`idlogin` ASC),
  INDEX `fk_filme_has_login_filme_idx` (`idfilme` ASC),
  PRIMARY KEY (`idpreferencia_usuario`),
  CONSTRAINT `fk_filme_has_login_filme`
    FOREIGN KEY (`idfilme`)
    REFERENCES `moviealert`.`filme` (`idfilme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filme_has_login_login1`
    FOREIGN KEY (`idlogin`)
    REFERENCES `moviealert`.`login` (`idlogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
